version: '3.5'

services:

  consul:
    image: consul
    command: agent -server -ui -node=server1 -bootstrap-expect=1 -client=0.0.0.0
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    networks:
      - challenge
  dbpostgresql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=account-service
    networks:
      - challenge
    volumes:
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql

  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "root@email.com"
      PGADMIN_DEFAULT_PASSWORD: "s3cr3t"
    ports:
      - "16543:80"
    depends_on:
      - dbpostgresql
    networks:
      - challenge

  mongodb:
    image: mongo
    container_name: "mongodb"
    ports:
      - 27017:27017
    networks:
      - challenge

  account-service:
    restart: on-failure
    build:
      context: account-service
      dockerfile: ./docker/Dockerfile
    ports:
      - "7001:7000"
    networks:
      - challenge
    depends_on:
      - dbpostgresql

  transaction-service:
    restart: on-failure
    build:
      context: transaction-service
      dockerfile: ./docker/Dockerfile
    ports:
      - "7002:7000"
    networks:
      - challenge
    depends_on:
      - mongodb

  api-gateway:
    restart: on-failure
    build:
      context: api-gateway
      dockerfile: ./docker/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - challenge

networks:
  challenge:
    driver: bridge