spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/account/**
        - id: transaction-service
          uri: lb://transaction-service
          predicates:
            - Path=/transaction/**
    consul:
      enabled: true
      host: consul
      port: 8500
      discovery:
        register: true
        registerHealthCheck: true
server:
  port: ${PORT:8080}