spring:
  application:
    name: account-service
  datasource:
    url: jdbc:postgresql://localhost:5432/tests
    username: postgres
    password: postgres
    initialization-mode: "always"
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: public
  batch:
    initialize-schema: "always"
  cloud:
    consul:
      enabled: true
      host: localhost
      port: 8500


management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 7000